spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/gardening_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
jwt:
  secret: WvdabkOgRJ56bjWBOn28J0b9p1Z+zVE41j8WiF4YXrk=